github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/kajabi-video-downloader",
"https://serp.co/products/kajabi-video-downloader/reviews/",
"https://whop.com/serp-downloaders/kajabi-video-downloader/"
]
